/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f303xc.h"
#include "initialisation.h"
#include "button.h"
#include "timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//function pointer to a function when a button is pressed, set to NULL so when it not assigned to any
//specific function it wont be called
void (*button_pressed)() = 0x00;

void EXTI0_IRQHandler()
{
	//call function button_pressed if its not NULL pointer
	if (button_pressed != 0x00)
	{
		button_pressed();
	}

	//reset interrupt
	EXTI->PR |= EXTI_PR_PR0;

}

int main(void)
{
    //settings for the boards
	enable_clocks();

	initialise_board();

	button_pressed = led_flag_on;

	enable_interrupt_button();

	start_timer();

	uint32_t time_length = 0x00800000;

	/*loop forever*/
	for(;;)
	{
		if((EXTI->EMR && 1) == 1)
		{
			modify_led();
		}
		timer_loop(time_length);
	}
}
