/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "serial.h"
#include "stm32f303xc.h"

#define BUFFER_SIZE 10

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void finished_transmission(uint32_t bytes_sent) {
//	// This function will be called after a transmission is complete
//
//	volatile uint32_t test = 0;
//	// make a very simple delay
//	for (volatile uint32_t i = 0; i < 0x8ffff; i++) {
//		// waste time !
//	}
}

//void enable_uart_interrupt(){
//	__disable_irq();
//
//	// enable system configuration controller
//	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
//
//	// EXTI Line 25 Interrupt
//	// set the pin to read to call the interrupt - USART1 receives over PA10
//	SYSCFG->EXTICR[5] = SYSCFG_EXTICR3_EXTI10_PA;
//
//	// Select EXTI25 on rising edge
//	EXTI->RTSR |= EXTI_RTSR_TR25
//
//
//	__enable_irq();
//}

int main(void)
{
	uint8_t buffer[BUFFER_SIZE] = {0};

	//void (*completion_function)(uint32_t) = &finished_transmission;

	SerialInitialise(BAUD_115200, &USART1_PORT, &finished_transmission);

	/* Loop forever */
	for(;;) {
		SerialReceiveString(&USART1_PORT);
//		SerialOutputString(buffer, &USART1_PORT);
	}
}
