/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "config.h"
#include "stm32f303xc.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



// Define callback functions for various interrupts
void (*tim3_overflow_callback)() = 0x00;
void (*tim2_ccr1_callback)() = 0x00;





int main(void)
{
	tim3_overflow_callback = 0x00;
	tim2_ccr1_callback = 0x00;

	enable_clocks();  // for GPIOA, C, E, and timers 2 and 3
	initialise_board();  // set LEDs to output mode
	set_prescaler(TIM2, PRESCALER);  // 1 count = 1 millisecond
	set_prescaler(TIM3, PRESCALER);  // 1 count = 1 millisecond
	set_autoreload(TIM3, INTERVAL_MS);
	config_tim2_interrupts();  // timer 2 is used for the one-shot delay
	config_tim3_interrupts();  // timer 3 is used for the periodic callback
	config_button_interrupts();


	// Change the timer period based on a condition or a new requirement
	uint16_t new_period = INTERVAL_MS;
	set_timer_period(new_period);


	// Set the function pointers used in the interrupt handlers
	// to their corresponding callback functions
	tim3_overflow_callback = &chase_led;


	// Start the timer 2 counter
	TIM2->CR1 |= TIM_CR1_CEN;

	// Start the timer 3 counter
	TIM3->CR1 |= TIM_CR1_CEN;

	turn_on_led(0b1);

	// Loop forever
	while (1) {}


}



